name: deployment
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_run:
    workflows: ["Playwright Test"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/${{secrets.project}}:latest, ${{ secrets.DOCKER_USERNAME }}/${{secrets.project}}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd dashboard-frontend
            docker-compose pull
            docker-compose down
            docker-compose up -d
